version: '3.7'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/checkapp

  mongo:
    image: mongo:bionic

